settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: weikung-com
    name: Quintin Shaw Blog
    url: 'https://weikung.com/'
    method: GET
    expectStatus: 200

  - id: oneindex
    name: Historical Pictures Hosting
    url: 'https://p1-img.bug.im/'
    method: GET
    expectStatus: 200
    
  - id: lsky
    name: Pictures Hosting
    url: 'https://images.kpfd.com/'
    method: GET
    expectStatus: 200
    
  - id: kpfd
    name: Keep Friends
    url: 'https://kpfd.com/'
    method: GET
    expectStatus: 200

  - id: 365-api
    name: 365 Day API
    url: 'https://api.365.day/v1'
    method: GET
    expectStatus: 200

  - id: 365-day
    name: 365 Day
    url: 'https://365.day/'
    method: GET
    expectStatus: 200







